// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxG8KK0_Pqp8Vzz6mx2tBlFrekp6qcuFc',
    appId: '1:1007577839454:web:aaed90ad439d9452a801cf',
    messagingSenderId: '1007577839454',
    projectId: 'students-165d7',
    authDomain: 'students-165d7.firebaseapp.com',
    storageBucket: 'students-165d7.appspot.com',
    measurementId: 'G-94J945ZX9J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2xX7RGGCA8Ubn51v697ccd3IAwlIDnzU',
    appId: '1:1007577839454:android:f5b187f23e12d5e1a801cf',
    messagingSenderId: '1007577839454',
    projectId: 'students-165d7',
    storageBucket: 'students-165d7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNErRbyftu41snvOgnjsxjnAz3pRMB-IU',
    appId: '1:1007577839454:ios:02b7977f863ee28ca801cf',
    messagingSenderId: '1007577839454',
    projectId: 'students-165d7',
    storageBucket: 'students-165d7.appspot.com',
    iosClientId: '1007577839454-gpa7k235gjsurtcekmcbcn3766pharfs.apps.googleusercontent.com',
    iosBundleId: 'com.example.dmentiaFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNErRbyftu41snvOgnjsxjnAz3pRMB-IU',
    appId: '1:1007577839454:ios:02b7977f863ee28ca801cf',
    messagingSenderId: '1007577839454',
    projectId: 'students-165d7',
    storageBucket: 'students-165d7.appspot.com',
    iosClientId: '1007577839454-gpa7k235gjsurtcekmcbcn3766pharfs.apps.googleusercontent.com',
    iosBundleId: 'com.example.dmentiaFlutterApp',
  );
}
